# Generated by Django 3.2.5 on 2021-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedaddress',
            name='id',
        ),
        migrations.AlterField(
            model_name='linkedaddress',
            name='primary_key',
            field=models.CharField(max_length=151, primary_key=True, serialize=False, verbose_name='verbose primary key'),
        ),
    ]
